### ISSUE TITLE
Setting up CVMFS on northgrid.gridpp.ac.uk

### ISSUE THREAD

**Issue by ickc** [simonsobs-uk/data-centre#20]
@rwf14f, what are the required steps to setup CVMFS with souk.ac.uk? If there are blocking items, can we write to northgrid for now? What are the necessary steps to have write access? Thanks.

**Comment by ickc** [comment]
Assigned @afortiorama as it seems it was suggested in the past.

**Comment by ickc** [comment]
Copied from email:

> since you created a separate VO we will need to make a formal request to gridpp/RAL.

**Comment by afortiorama** [comment]
Quoting from RAL email

> There are 2 ways for you to do it:
> 
>     the person who will do it needs to register in EGI CheckIn and send me the voperson_id, and then just ssh ( ssh [northgridsgm@cvmfs-upload01.gridpp.rl.ac.uk](mailto:northgridsgm@cvmfs-upload01.gridpp.rl.ac.uk) )
>     or send me the CN from their X509 cert and gsissh ( gsissh -p 1975[ northgridsgm@cvmfs-upload01.gridpp.rl.ac.uk](mailto:northgridsgm@cvmfs-upload01.gridpp.rl.ac.uk)   )
> 
> 
> If possible, the first method would be better. 
> 
> Currently I don’t have any individual registered in the service. 
> Only DN associated to this repository is "/vo.northgrid.ac.uk/Role=lcgadmin/Capability=NULL”

More instructions are here https://www.gridpp.ac.uk/wiki/CVMFS

**Comment by afortiorama** [comment]
The northgrid CVMFS path is 

/cvmfs/northgrid.gridpp.ac.uk

**Comment by ickc** [comment]
Applying by following the instruction there and sent an email to <cvmfs-support@gridpp.rl.ac.uk>, one thing I'm not so sure is how I might obtain the `voperson_id`, and I'm just guessing it is the username I see from <https://aai.egi.eu/auth/realms/egi/account/#/personal-info>.

**Comment by ickc** [comment]
Hi, @afortiorama, I now can write to the North Grid CVMFS. But what is the typical time scale for it to appears on Blackett nodes for example after I write stuffs there?

**Comment by rwf14f** [comment]
@afortiorama and @rwf14f have both access to the cvmfs publishing machine. If you give us a tarball with the compiled software we can upload it to cvmfs. The most important bit is that you use a installation prefix that's below `/cvmfs/northgrid.gridpp.ac.uk/souk` (referred to as `<prefix>` below).
You should also consider having a sensible structure that includes versioning, eg
`<prefix>/<collection>_<version>/<tool>_<version>/<flavour>/`.
This structure is mainly aimed at libraries and software that is specifically compiled for specific OS / compiler combinations and might not be necessary in your case. This is just an example, you don't have to structure it the exact same way.
It's also advisable to have setup scripts in cvmfs which can be sourced by the user to set the environment variables required to use the software that's in cvmfs.

**Comment by ickc** [comment]
Hi, @rwf14f, I have write access and I know about prefix (which is explained in our documentation in <https://souk-data-centre.readthedocs.io/en/latest/user/pipeline/2-software-deployment/1-tarball/#prefix-directory-and-software-deployment> for example). I already made a directory `/cvmfs/northgrid.gridpp.ac.uk/simonsobservatory` (which is the group we have on `vm77`) there but of course we could use `souk` too (in that case I think `souk.ac.uk` makes more sense?)

But the question is really how long am I suppose to see files written there to be seen somewhere else? I think there's some synchronization interval? What number is set there?

Thanks.

**Comment by rwf14f** [comment]
> Hi, @afortiorama, I now can write to the North Grid CVMFS. But what is the typical time scale for it to appears on Blackett nodes for example after I write stuffs there?

We haven't used it in a while, but if I remember correctly it should be within an hour.

**Comment by ickc** [comment]
Thanks. Any opinion of the name of the subdir? `simonsobservatory`, `souk`, `souk.ac.uk`?

**Comment by rwf14f** [comment]
I don't have a preference there, use whichever you want.
