### ISSUE TITLE
Mounting grid from vm77 not working

### ISSUE THREAD

**Issue by earosenberg** [simonsobs-uk/data-centre#29]
Trying to mount the grid storage from vm77 as per these instructions https://souk-data-centre.readthedocs.io/en/latest/user/pipeline/4-IO/1-grid-storage-system/4-xrootdfs/.
This worked a few weeks ago. Now when I run `/opt/simonsobservatory/xrootdfs.sh start` it creates the directory souk.ac.uk in my $HOME and the script doesn't complain.
Then running `ls` in $HOME gives the error:
`ls: cannot access souk.ac.uk: No such file or directory`.
After `/opt/simonsobservatory/xrootdfs.sh stop` the error message disappears and souk.ac.uk becomes a normal empty directory.

`gfal-ls root://bohr3226.tier2.hep.manchester.ac.uk:1094//dpm/tier2.hep.manchester.ac.uk/home/souk.ac.uk/` works fine on the other hand.

**Comment by rwf14f** [comment]
Works fine for me with:
```
xrootdfs <mount point> -o rdr=root://bohr3226.tier2.hep.manchester.ac.uk:1094//dpm/tier2.hep.manchester.ac.uk/home/souk.ac.uk/ -o umask=0077 -o default_permissions
```
Please make sure you have a valid voms proxy when mounting the directory. If the proxy expires while the directory is mounted is also going to cause problems.

**Comment by earosenberg** [comment]
Thanks -- that command works for me too.
It turns out that removing the line `cd \tmp` from the script makes it work for me. The problem seems to be that the proxy is only recognized as active when executing commands from my home directory, where `ac.pem` is located; `gfal` commands are asking for my password when run from other directories.
Am I missing some setting for making the proxy visible from anywhere or is this expected behaviour? The proxy is being set with `voms-proxy-init -valid 168:00 -voms souk.ac.uk`.

**Comment by ickc** [comment]
From my examples in the documentation, `ac.pem` is only used when submitting jobs (where the ClassAd is transferring this file to the worker node, and then within your script `ac.pem` is further pointed to by an env. var.)

If you mount the xrootdfs, it should uses the one created by voms-rpoxy-init automatically.

Do you still have trouble getting that working or was that fixed already?

**Comment by earosenberg** [comment]
Thanks Kolen that explains it.
I had (mistakenly) added `export X509_USER_PROXY=ac.pem` to by .bashrc on the vm77 so it was looking for that instead of using the default. Removing that line makes the script and gfal commands work as expected. 
Thanks both for the help.
