### ISSUE TITLE
Intermittent Network Overloads and Connection Drops When Accessing Blackett from UoM

### ISSUE THREAD

**Issue by ickc** [simonsobs-uk/data-centre#8]
According to conversations between @rwf14f, @shaikhhasib, this is a known problem, and a temporary fix is to connect to it from outside UoM.

Edit: symptom and background: UoM has its own firewall and Blackett while geographically located within UoM, has their own firewall outside UoM. Connections from within UoM to Blackett are mostly fine, but sometimes it will just disconnect and succeeding reconnection refused.

**Comment by ickc** [comment]
@shaikhhasib, have you experienced the same issue lately? Do you know if it was fixed already?

**Comment by shaikhhasib** [comment]
@ickc, its hasn't change, it break the connection

**Comment by ickc** [comment]
Thanks.

By the way, did @earosenberg experience this too? Is it a big problem?

**Comment by earosenberg** [comment]
I've had slow data transfer rates (~45 mins to transfer 1GB python tarball from my laptop by sftp) but not sure if this is the same problem

**Comment by ickc** [comment]
@earosenberg, sorry, this issue is not well documented. I changed the title and add a text:

> symptom and background: UoM has its own firewall and Blackett while geographically located within UoM, has their own firewall outside UoM. Connections from within UoM to Blackett are mostly fine, but sometimes it will just disconnect and succeeding reconnection refused.

Regarding throughput from your laptop, I'll open a new issue tracking that.

**Comment by ickc** [comment]
From an internal conversation, it seems that an internal link is saturating so it is a "won't fix".
