### ISSUE TITLE
some services require elevated permissions which is not permitted on our testbed vm77

### ISSUE THREAD

**Issue by ickc** [simonsobs-uk/data-centre#9]
E.g. @shaikhhasib needs to run PostgreSQL but we don't have sudo power on vm77. @shaikhhasib already asked @rwf14f if a VM with sudo power can be granted for us.

**Comment by shaikhhasib** [comment]
@rwf14f Is there any update on this? It would be nice if we can get few nodes where we can run some of our web service!!

**Comment by rwf14f** [comment]
You can install it on vm77. Please be aware that CentOS 7 only has 9.2.24.
Repo files are managed by Puppet which will remove all unknown files in /etc/yum.repos.d/.

**Comment by shaikhhasib** [comment]
@rwf14f  never mind fix the issue with  **sudo** sudo systemctl start postgresql

**Comment by ickc** [comment]
Thanks, @rwf14f, we both now have sudo (in the wheel group) on vm77. Closing.
